const KEY='nounouIA.v3';
const now=new Date(),CY=now.getFullYear();
const MONTHS=['janvier','février','mars','avril','mai','juin','juillet','août','septembre','octobre','novembre','décembre'];
const MN=['janvier','fevrier','mars','avril','mai','juin','juillet','aout','septembre','octobre','novembre','decembre'];
const WD=['Lun','Mar','Mer','Jeu','Ven','Sam','Dim'];
const LABEL={garde:'Gardé',exceptionnel:'Exceptionnel',vacances_parent:'Vacances famille',conge:'Congé nounou',absence_enfant:'Absence enfant',absence_nounou:'Absence nounou',non_prevu:'Non prévu'};
const def={settings:{childName:'Warrel',nannyName:'',hourlyRate:4.5,careFee:3.8,mealFee:4,defaultStart:'08:00',defaultEnd:'17:30',periodStart:CY+'-01-01',periodEnd:CY+'-12-31',standardDays:[1,2,4,5],aiEndpoint:''},days:{},year:CY,month:now.getMonth(),chat:[{role:'bot',text:'Écris une phrase simple : vacances du 05/08 au 23/08 ou combien payer ce mois-ci.'}]};
let state=load(),installPrompt=null;
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],EX=['vacances_parent','conge'];
function load(){try{const raw=localStorage.getItem(KEY)||localStorage.getItem('nounouIA.v1');if(!raw)return JSON.parse(JSON.stringify(def));const s=JSON.parse(raw);return {...def,...s,settings:{...def.settings,...(s.settings||{})},days:s.days||{},chat:s.chat||def.chat}}catch(e){return JSON.parse(JSON.stringify(def))}}
function save(){localStorage.setItem(KEY,JSON.stringify(state))}
function key(d){return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0')}
function date(k){let a=k.split('-').map(Number);return new Date(a[0],a[1]-1,a[2])}
function norm(t){return String(t).toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'')}
function min(t){if(!t)return 0;let a=t.split(':').map(Number);return a[0]*60+a[1]}
function hBetween(a,b){let x=min(a),y=min(b);if(y<x)y+=1440;return Math.max(0,y-x)/60}
function hours(d){return d&&['garde','exceptionnel'].includes(d.status)?Math.max(0,hBetween(d.start,d.end)-Number(d.pause||0)/60):0}
function euro(v){return Number(v||0).toFixed(2).replace('.',',')+' €'}
function htxt(v){let m=Math.round((v||0)*60);return Math.floor(m/60)+'h'+String(m%60).padStart(2,'0')}
function cost(d){return hours(d)*Number(state.settings.hourlyRate||0)+(d&&d.care?Number(state.settings.careFee||0):0)+(d&&d.meal?Number(state.settings.mealFee||0):0)}
function line(a,b){return '<div class="line"><span>'+a+'</span><strong>'+b+'</strong></div>'}
function toast(t){let e=$('#toast');e.textContent=t;e.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.remove('show'),2600)}
function gridDates(y,m){let f=new Date(y,m,1),off=(f.getDay()+6)%7,s=new Date(y,m,1-off);return Array.from({length:42},(_,i)=>new Date(s.getFullYear(),s.getMonth(),s.getDate()+i))}
function entries(y=state.year,m=state.month){return Object.entries(state.days).filter(([k])=>{let d=date(k);return d.getFullYear()==y&&d.getMonth()==m}).sort()}
function sum(){let s={h:0,days:0,meals:0,care:0,vac:0,hol:0,total:0,entries:entries()};for(let [,d] of s.entries){if(['garde','exceptionnel'].includes(d.status)){s.days++;s.h+=hours(d);s.total+=cost(d);if(d.meal)s.meals++;if(d.care)s.care++}if(d.status=='vacances_parent')s.vac++;if(d.status=='conge')s.hol++}return s}
function annualCalc(){let st=date(state.settings.periodStart||state.year+'-01-01'),en=date(state.settings.periodEnd||state.year+'-12-31'),std=state.settings.standardDays||[],possible=0,planned=0,excluded=0,weeks=new Set();for(let d=new Date(st);d<=en;d.setDate(d.getDate()+1)){if(!std.includes(d.getDay()))continue;possible++;let dy=state.days[key(d)];if(dy&&EX.includes(dy.status)){excluded++}else{planned++;weeks.add(weekKey(d))}}let per=std.length||1,dayH=hBetween(state.settings.defaultStart,state.settings.defaultEnd),weekH=dayH*per,wExact=planned/per,base=weekH*Number(state.settings.hourlyRate||0)*wExact/12;return{possible,planned,excluded,per,dayH,weekH,wExact,base,weeks:weeks.size,start:st,end:en}}
function weekKey(d){let x=new Date(d),o=(x.getDay()+6)%7;x.setDate(x.getDate()-o);return key(x)}
function annualHtml(){let a=annualCalc();return line('Période',key(a.start)+' au '+key(a.end))+line('Jours habituels / semaine',a.per)+line('Heures prévues / semaine',htxt(a.weekH))+line('Jours possibles',a.possible)+line('Jours exclus',a.excluded)+line('Jours programmés',a.planned)+line('Semaines exactes',a.wExact.toFixed(2).replace('.',','))+line('Base mensuelle hors repas/entretien',euro(a.base))+'<p class="hint">Calcul indicatif à vérifier avec le contrat et Pajemploi.</p>'}
function render(){let s=sum(),title=MONTHS[state.month]+' '+state.year;$('#subtitle').textContent='Suivi de '+(state.settings.childName||'l’enfant')+(state.settings.nannyName?' avec '+state.settings.nannyName:'')+'.';$('#monthTitle').textContent=title;$('#monthTitle2').textContent=title;$('#yearTitle').textContent='Calendrier '+state.year;$('#stats').innerHTML=[['Total',euro(s.total)],['Heures',htxt(s.h)],['Jours',s.days],['Repas',s.meals]].map(x=>'<div class="stat"><span>'+x[0]+'</span><strong>'+x[1]+'</strong></div>').join('');$('#summary').innerHTML=line('Heures réalisées',htxt(s.h))+line('Jours de garde',s.days)+line('Repas',s.meals)+line('Entretien',s.care)+line('Vacances famille',s.vac)+line('Congés nounou',s.hol)+line('Montant estimé',euro(s.total));if($('#annualSummary'))$('#annualSummary').innerHTML=annualHtml();if($('#annualSummaryHome'))$('#annualSummaryHome').innerHTML=annualHtml();renderMonth();renderAnnual();renderYears();renderSettings();renderChat();renderVacList()}
function renderMonth(){let today=key(new Date()),ds=gridDates(state.year,state.month);$('#monthGrid').innerHTML=WD.map(d=>'<div class="wd">'+d+'</div>').join('')+ds.map(d=>{let k=key(d),dy=state.days[k];return '<button class="day '+(d.getMonth()!=state.month?'out ':'')+(k==today?'today ':'')+(dy?'bg-'+dy.status:'')+'" data-date="'+k+'">'+d.getDate()+(dy?'<span class="meta">'+LABEL[dy.status]+'</span><span class="amount">'+(cost(dy)?euro(cost(dy)):'')+'</span>':'')+'</button>'}).join('');$$('.day').forEach(b=>b.onclick=()=>openDay(b.dataset.date))}
function renderAnnual(){let today=key(new Date());$('#annual').innerHTML=Array.from({length:12},(_,m)=>'<article class="month-card"><h3>'+MONTHS[m]+'</h3><div class="mini">'+WD.map(d=>'<div class="wd">'+d+'</div>').join('')+gridDates(state.year,m).map(d=>{let k=key(d),dy=state.days[k];return '<button class="mini-day '+(d.getMonth()!=m?'out ':'')+(k==today?'today ':'')+(dy?'bg-'+dy.status:'')+'" data-date="'+k+'">'+d.getDate()+'</button>'}).join('')+'</div></article>').join('');$$('.mini-day').forEach(b=>b.onclick=()=>openDay(b.dataset.date))}
function renderYears(){let c=new Date().getFullYear();$('#yearSelect').innerHTML=Array.from({length:7},(_,i)=>c-2+i).map(y=>'<option '+(y==state.year?'selected':'')+'>'+y+'</option>').join('')}
function renderSettings(){let s=state.settings;$('#child').value=s.childName||'';$('#nanny').value=s.nannyName||'';$('#rate').value=s.hourlyRate;$('#careFee').value=s.careFee;$('#mealFee').value=s.mealFee;$('#defStart').value=s.defaultStart;$('#defEnd').value=s.defaultEnd;if($('#periodStart'))$('#periodStart').value=s.periodStart||state.year+'-01-01';if($('#periodEnd'))$('#periodEnd').value=s.periodEnd||state.year+'-12-31';$('#endpoint').value=s.aiEndpoint||'';$$('input[name="std"]').forEach(i=>i.checked=(s.standardDays||[]).includes(Number(i.value)))}
function renderChat(){let esc=t=>String(t).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));$('#chat').innerHTML=state.chat.slice(-30).map(m=>'<div class="msg '+(m.role=='user'?'user':'bot')+'">'+esc(m.text).replaceAll('\n','<br>')+'</div>').join('');$('#chat').scrollTop=$('#chat').scrollHeight}
function openDay(k){let d=date(k),dy=state.days[k]||{};state.year=d.getFullYear();state.month=d.getMonth();$('#dayDate').value=k;$('#status').value=dy.status||'garde';$('#start').value=dy.start||state.settings.defaultStart;$('#end').value=dy.end||state.settings.defaultEnd;$('#pause').value=dy.pause||0;$('#meal').checked=dy.meal??true;$('#care').checked=dy.care??true;$('#note').value=dy.note||'';show('add');save();render()}
function show(v){$$('.view').forEach(e=>e.classList.toggle('active',e.id==v));$$('nav button').forEach(b=>b.classList.toggle('active',b.dataset.v==v))}
function saveDay(e){e.preventDefault();let k=$('#dayDate').value,st=$('#status').value;state.days[k]={status:st,start:$('#start').value,end:$('#end').value,pause:Number($('#pause').value||0),meal:$('#meal').checked,care:$('#care').checked,note:$('#note').value.trim()};if(EX.includes(st)){state.days[k].start='';state.days[k].end='';state.days[k].meal=false;state.days[k].care=false}let d=date(k);state.year=d.getFullYear();state.month=d.getMonth();save();render();toast('Journée enregistrée')}
function delDay(){let k=$('#dayDate').value;if(state.days[k]){delete state.days[k];save();render();toast('Journée supprimée')}}
function saveSettings(e){e.preventDefault();state.settings={...state.settings,childName:$('#child').value.trim(),nannyName:$('#nanny').value.trim(),hourlyRate:Number($('#rate').value||0),careFee:Number($('#careFee').value||0),mealFee:Number($('#mealFee').value||0),defaultStart:$('#defStart').value,defaultEnd:$('#defEnd').value,periodStart:$('#periodStart')?.value||state.year+'-01-01',periodEnd:$('#periodEnd')?.value||state.year+'-12-31',aiEndpoint:$('#endpoint').value.trim(),standardDays:$$('input[name="std"]:checked').map(i=>Number(i.value))};save();render();toast('Réglages sauvegardés')}
function fillMonth(){let n=0,s=state.settings,last=new Date(state.year,state.month+1,0).getDate();for(let i=1;i<=last;i++){let d=new Date(state.year,state.month,i),k=key(d);if(!s.standardDays.includes(d.getDay())||state.days[k])continue;state.days[k]={status:'garde',start:s.defaultStart,end:s.defaultEnd,pause:0,meal:true,care:true,note:'Journée habituelle'};n++}save();render();toast(n+' jour(s) ajouté(s)')}
function parseRange(t){let l=norm(t),m=l.match(/(\d{1,2})[\/\-](\d{1,2})(?:[\/\-](\d{2,4}))?.{0,20}?(?:au|a|-)(\d{1,2})[\/\-](\d{1,2})(?:[\/\-](\d{2,4}))?/);if(m)return{start:new Date(m[3]?yr(m[3]):state.year,m[2]-1,m[1]),end:new Date(m[6]?yr(m[6]):(m[3]?yr(m[3]):state.year),m[5]-1,m[4])};let mons=MN.join('|');m=l.match(new RegExp('du\\s+(\\d{1,2}).*?(?:au|a)\\s+(\\d{1,2})\\s+('+mons+')(?:\\s+(\\d{4}))?'));if(m){let mo=MN.indexOf(m[3]),y=m[4]?Number(m[4]):state.year;return{start:new Date(y,mo,m[1]),end:new Date(y,mo,m[2])}}return null}
function yr(y){y=Number(y);return y<100?2000+y:y}
function applyVac(t){let r=parseRange(t);if(!r)return 'Dates non comprises. Exemple : vacances du 05/08 au 23/08.';let st=r.start,en=r.end;if(en<st){let x=st;st=en;en=x}let status=norm(t).includes('nounou')?'conge':'vacances_parent',n=0;for(let d=new Date(st);d<=en;d.setDate(d.getDate()+1)){state.days[key(d)]={status,start:'',end:'',pause:0,meal:false,care:false,note:'Période saisie'}}state.year=st.getFullYear();state.month=st.getMonth();save();let a=annualCalc();return LABEL[status]+' ajouté : '+key(st)+' au '+key(en)+'\nSemaines exactes : '+a.wExact.toFixed(2).replace('.',',')+'\nBase mensuelle : '+euro(a.base)}
function renderVacList(){let b=$('#vacationList');if(!b)return;let ks=Object.keys(state.days).filter(k=>date(k).getFullYear()==state.year&&EX.includes(state.days[k].status)).sort();b.innerHTML=ks.length?ks.map(k=>line(k,LABEL[state.days[k].status])).join(''):'<p class="hint">Aucune période sur cette année.</p>'}
function clearVacations(){for(let k of Object.keys(state.days)){if(date(k).getFullYear()==state.year&&EX.includes(state.days[k].status))delete state.days[k]}save();render();toast('Vacances supprimées')}
function localAI(t){let l=norm(t);if(l.includes('vacance')||l.includes('conge'))return applyVac(t);if(l.includes('combien')||l.includes('payer')||l.includes('mensualisation')){let s=sum(),a=annualCalc();return 'Mois : '+euro(s.total)+'\nAnnée incomplète : '+a.wExact.toFixed(2).replace('.',',')+' semaines\nBase mensuelle hors repas/entretien : '+euro(a.base)}return 'Je peux ajouter des vacances ou calculer le mois.'}
async function ask(e){e.preventDefault();let t=$('#ask').value.trim();if(!t)return;state.chat.push({role:'user',text:t});$('#ask').value='';let r=localAI(t);state.chat.push({role:'bot',text:r});save();render()}
function backup(){let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(state,null,2)],{type:'application/json'}));a.download='sauvegarde-nounou-ia.json';a.click()}
function importBackup(f){if(!f)return;let r=new FileReader();r.onload=()=>{state={...def,...JSON.parse(r.result)};save();render()};r.readAsText(f)}
function bind(){$$('nav button').forEach(b=>b.onclick=()=>show(b.dataset.v));$('#prev').onclick=()=>{let d=new Date(state.year,state.month-1,1);state.year=d.getFullYear();state.month=d.getMonth();save();render()};$('#next').onclick=()=>{let d=new Date(state.year,state.month+1,1);state.year=d.getFullYear();state.month=d.getMonth();save();render()};$('#yearSelect').onchange=e=>{state.year=Number(e.target.value);save();render()};$('#fillMonth').onclick=fillMonth;$('#csv').onclick=()=>toast('Export CSV sera remis dans la prochaine mise à jour');$('#print').onclick=()=>window.print();$('#dayForm').onsubmit=saveDay;$('#deleteDay').onclick=delDay;$('#settingsForm').onsubmit=saveSettings;$('#assistantForm').onsubmit=ask;$('#backup').onclick=backup;$('#import').onchange=e=>importBackup(e.target.files[0]);if($('#vacationForm'))$('#vacationForm').onsubmit=e=>{e.preventDefault();toast(applyVac($('#vacationText').value));render()};if($('#clearVacations'))$('#clearVacations').onclick=clearVacations;$$('.examples button').forEach(b=>b.onclick=()=>{let v=$('#vacationText')&&b.closest('.vacation-examples');(v?$('#vacationText'):$('#ask')).value=b.textContent});$('#dayDate').value=key(new Date())}
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e;$('#installBtn').hidden=false;$('#installBtn').onclick=()=>{installPrompt.prompt();$('#installBtn').hidden=true}});
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('sw.js').catch(console.warn));
bind();render();
