const KEY="nounouIA.v1";
const MONTHS=["janvier","février","mars","avril","mai","juin","juillet","août","septembre","octobre","novembre","décembre"];
const WD=["Lun","Mar","Mer","Jeu","Ven","Sam","Dim"];
const LABEL={garde:"Gardé",exceptionnel:"Exceptionnel",conge:"Congé",absence_enfant:"Absence enfant",absence_nounou:"Absence nounou",non_prevu:"Non prévu"};
const def={settings:{childName:"Warrel",nannyName:"",hourlyRate:4.5,overtimeRate:0,careFee:3.8,mealFee:4,defaultStart:"08:00",defaultEnd:"17:30",standardDays:[1,2,4,5],aiEndpoint:""},days:{},year:new Date().getFullYear(),month:new Date().getMonth(),chat:[{role:"bot",text:"Écris une phrase simple. Exemple : “Ajoute demain de 8h à 17h30” ou “Combien je dois payer ce mois-ci ?”."}]};
let state=load();
let installPrompt=null;
const $=s=>document.querySelector(s);
const $$=s=>[...document.querySelectorAll(s)];
function clone(x){return JSON.parse(JSON.stringify(x))}
function load(){try{const r=localStorage.getItem(KEY);if(!r)return clone(def);const s=JSON.parse(r);return {...clone(def),...s,settings:{...clone(def.settings),...(s.settings||{})},days:s.days||{},chat:Array.isArray(s.chat)?s.chat:clone(def.chat)}}catch(e){return clone(def)}}
function save(){localStorage.setItem(KEY,JSON.stringify(state))}
function key(d){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`}
function date(k){const [y,m,d]=k.split("-").map(Number);return new Date(y,m-1,d)}
function human(k){return date(k).toLocaleDateString("fr-FR",{weekday:"long",day:"2-digit",month:"long",year:"numeric"})}
function min(t){if(!t||!t.includes(":"))return 0;const [h,m]=t.split(":").map(Number);return h*60+m}
function hours(day){if(!day||!["garde","exceptionnel"].includes(day.status))return 0;let a=min(day.start),b=min(day.end);if(b<a)b+=1440;return Math.max(0,b-a-Number(day.pause||0))/60}
function euro(v){return `${Number(v||0).toFixed(2).replace(".",",")} €`}
function htxt(v){const m=Math.round(Number(v||0)*60),h=Math.floor(m/60),r=m%60;return `${h}h${String(r).padStart(2,"0")}`}
function cost(day){if(!day||!["garde","exceptionnel"].includes(day.status))return 0;return hours(day)*Number(state.settings.hourlyRate||0)+(day.care?Number(state.settings.careFee||0):0)+(day.meal?Number(state.settings.mealFee||0):0)}
function entries(y=state.year,m=state.month){return Object.entries(state.days).filter(([k])=>{const d=date(k);return d.getFullYear()===y&&d.getMonth()===m}).sort(([a],[b])=>a.localeCompare(b))}
function sum(y=state.year,m=state.month){const s={h:0,days:0,meals:0,care:0,childAbs:0,nannyAbs:0,hol:0,total:0,entries:entries(y,m)};for(const[,d]of s.entries){if(["garde","exceptionnel"].includes(d.status)){s.days++;s.h+=hours(d);if(d.meal)s.meals++;if(d.care)s.care++;s.total+=cost(d)}if(d.status==="absence_enfant")s.childAbs++;if(d.status==="absence_nounou")s.nannyAbs++;if(d.status==="conge")s.hol++}return s}
function toast(t){const e=$("#toast");e.textContent=t;e.classList.add("show");clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.remove("show"),2500)}
function gridDates(y,m){const f=new Date(y,m,1),off=(f.getDay()+6)%7,start=new Date(y,m,1-off);return Array.from({length:42},(_,i)=>new Date(start.getFullYear(),start.getMonth(),start.getDate()+i))}
function bg(d){return d?`bg-${d.status}`:""}
function render(){const s=sum(),title=`${MONTHS[state.month]} ${state.year}`;$("#subtitle").textContent=`Suivi de ${state.settings.childName||"l’enfant"}${state.settings.nannyName?" avec "+state.settings.nannyName:""}.`;$("#monthTitle").textContent=title;$("#monthTitle2").textContent=title;$("#yearTitle").textContent=`Calendrier ${state.year}`;$("#stats").innerHTML=[["Total",euro(s.total)],["Heures",htxt(s.h)],["Jours",s.days],["Repas",s.meals]].map(x=>`<div class="stat"><span>${x[0]}</span><strong>${x[1]}</strong></div>`).join("");$("#summary").innerHTML=[["Enfant",state.settings.childName||"Non renseigné"],["Assistante maternelle",state.settings.nannyName||"Non renseignée"],["Heures réalisées",htxt(s.h)],["Jours de garde",s.days],["Entretien",s.care],["Repas",s.meals],["Absences enfant",s.childAbs],["Absences nounou",s.nannyAbs],["Congés",s.hol],["Montant estimé",euro(s.total)]].map(x=>`<div class="line"><span>${x[0]}</span><strong>${x[1]}</strong></div>`).join("");renderMonth();renderAnnual();renderYears();renderSettings();renderChat()}
function renderMonth(){const today=key(new Date()),ds=gridDates(state.year,state.month);$("#monthGrid").innerHTML=WD.map(d=>`<div class="wd">${d}</div>`).join("")+ds.map(d=>{const k=key(d),day=state.days[k],out=d.getMonth()!==state.month?"out":"",td=k===today?"today":"";return `<button class="day ${out} ${td} ${bg(day)}" data-date="${k}">${d.getDate()}${day?`<span class="meta">${LABEL[day.status]}${hours(day)?" · "+htxt(hours(day)):""}</span><span class="amount">${cost(day)?euro(cost(day)):""}</span>`:""}</button>`}).join("");$$('.day').forEach(b=>b.onclick=()=>openDay(b.dataset.date))}
function renderAnnual(){const today=key(new Date());$("#annual").innerHTML=Array.from({length:12},(_,m)=>{const ds=gridDates(state.year,m);return `<article class="month-card"><h3>${MONTHS[m]}</h3><div class="mini">${WD.map(d=>`<div class="wd">${d}</div>`).join("")}${ds.map(d=>{const k=key(d),day=state.days[k];return `<button class="mini-day ${d.getMonth()!==m?"out":""} ${k===today?"today":""} ${bg(day)}" data-date="${k}">${d.getDate()}</button>`}).join("")}</div></article>`}).join("");$$('.mini-day').forEach(b=>b.onclick=()=>openDay(b.dataset.date))}
function renderYears(){const c=new Date().getFullYear();$("#yearSelect").innerHTML=Array.from({length:7},(_,i)=>c-2+i).map(y=>`<option ${y===state.year?"selected":""}>${y}</option>`).join("")}
function renderSettings(){const s=state.settings;$("#child").value=s.childName||"";$("#nanny").value=s.nannyName||"";$("#rate").value=s.hourlyRate;$("#careFee").value=s.careFee;$("#mealFee").value=s.mealFee;$("#overtime").value=s.overtimeRate;$("#defStart").value=s.defaultStart;$("#defEnd").value=s.defaultEnd;$("#endpoint").value=s.aiEndpoint||"";$$('input[name="std"]').forEach(i=>i.checked=(s.standardDays||[]).includes(Number(i.value)))}
function renderChat(){const esc=t=>String(t).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));$("#chat").innerHTML=state.chat.slice(-30).map(m=>`<div class="msg ${m.role==='user'?'user':'bot'}">${esc(m.text).replaceAll('\n','<br>')}</div>`).join("");$("#chat").scrollTop=$("#chat").scrollHeight}
function openDay(k){const d=date(k),day=state.days[k];state.year=d.getFullYear();state.month=d.getMonth();save();$("#dayDate").value=k;$("#status").value=day?.status||"garde";$("#start").value=day?.start||state.settings.defaultStart;$("#end").value=day?.end||state.settings.defaultEnd;$("#pause").value=day?.pause||0;$("#meal").checked=day?.meal??true;$("#care").checked=day?.care??true;$("#note").value=day?.note||"";show("add");render()}
function show(v){$$('.view').forEach(e=>e.classList.toggle('active',e.id===v));$$('nav button').forEach(b=>b.classList.toggle('active',b.dataset.v===v))}
function saveDay(e){e.preventDefault();const k=$("#dayDate").value;if(!k)return;state.days[k]={status:$("#status").value,start:$("#start").value,end:$("#end").value,pause:Number($("#pause").value||0),meal:$("#meal").checked,care:$("#care").checked,note:$("#note").value.trim()};const d=date(k);state.year=d.getFullYear();state.month=d.getMonth();save();render();toast("Journée enregistrée")}
function delDay(){const k=$("#dayDate").value;if(!state.days[k])return toast("Aucune journée à supprimer");if(confirm(`Supprimer ${human(k)} ?`)){delete state.days[k];save();render();toast("Journée supprimée")}}
function saveSettings(e){e.preventDefault();state.settings={...state.settings,childName:$("#child").value.trim(),nannyName:$("#nanny").value.trim(),hourlyRate:Number($("#rate").value||0),careFee:Number($("#careFee").value||0),mealFee:Number($("#mealFee").value||0),overtimeRate:Number($("#overtime").value||0),defaultStart:$("#defStart").value,defaultEnd:$("#defEnd").value,aiEndpoint:$("#endpoint").value.trim(),standardDays:$$('input[name="std"]:checked').map(i=>Number(i.value))};save();render();toast("Réglages sauvegardés")}
function fillMonth(){let n=0;const s=state.settings,last=new Date(state.year,state.month+1,0).getDate();for(let i=1;i<=last;i++){const d=new Date(state.year,state.month,i);if(!s.standardDays.includes(d.getDay()))continue;const k=key(d);if(state.days[k])continue;state.days[k]={status:"garde",start:s.defaultStart,end:s.defaultEnd,pause:0,meal:true,care:true,note:"Journée habituelle"};n++}save();render();toast(`${n} journée(s) ajoutée(s)`)}
function download(name,content,type="application/json"){const a=document.createElement("a"),u=URL.createObjectURL(new Blob([content],{type}));a.href=u;a.download=name;document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(u)}
function exportCsv(){const rows=[["Date","Statut","Début","Fin","Heures","Repas","Entretien","Note","Montant"]];for(const[k,d]of sum().entries)rows.push([k,LABEL[d.status]||d.status,d.start||"",d.end||"",htxt(hours(d)),d.meal?"oui":"non",d.care?"oui":"non",d.note||"",euro(cost(d))]);download(`nounou-${state.year}-${String(state.month+1).padStart(2,"0")}.csv`,rows.map(r=>r.map(c=>`"${String(c).replaceAll('"','""')}"`).join(";")).join("\n"),"text/csv;charset=utf-8")}
function printMonth(){const s=sum(),title=`${MONTHS[state.month]} ${state.year}`;$("#printArea").innerHTML=`<h1>Récapitulatif garde - ${title}</h1><p><b>Enfant :</b> ${state.settings.childName||""}</p><p><b>Assistante maternelle :</b> ${state.settings.nannyName||""}</p><p><b>Heures :</b> ${htxt(s.h)} - <b>Jours :</b> ${s.days} - <b>Total :</b> ${euro(s.total)}</p><table class="print-table"><thead><tr><th>Date</th><th>Statut</th><th>Horaires</th><th>Heures</th><th>Repas</th><th>Entretien</th><th>Montant</th><th>Note</th></tr></thead><tbody>${s.entries.map(([k,d])=>`<tr><td>${human(k)}</td><td>${LABEL[d.status]}</td><td>${d.start||""} - ${d.end||""}</td><td>${htxt(hours(d))}</td><td>${d.meal?"Oui":"Non"}</td><td>${d.care?"Oui":"Non"}</td><td>${euro(cost(d))}</td><td>${d.note||""}</td></tr>`).join("")}</tbody></table>`;setTimeout(()=>window.print(),50)}
function backup(){download(`sauvegarde-nounou-ia-${new Date().toISOString().slice(0,10)}.json`,JSON.stringify(state,null,2))}
function importBackup(f){if(!f)return;const r=new FileReader();r.onload=()=>{try{const x=JSON.parse(r.result);state={...clone(def),...x,settings:{...clone(def.settings),...(x.settings||{})},days:x.days||{}};save();render();toast("Sauvegarde importée")}catch(e){toast("Fichier invalide")}};r.readAsText(f)}
function parseDate(txt){const l=txt.toLowerCase(),t=new Date();if(l.includes("aujourd"))return t;if(l.includes("demain"))return new Date(t.getFullYear(),t.getMonth(),t.getDate()+1);const m=l.match(/(\d{1,2})\s*[\/\-]\s*(\d{1,2})(?:\s*[\/\-]\s*(\d{2,4}))?/);if(m)return new Date(m[3]?norm(Number(m[3])):state.year,Number(m[2])-1,Number(m[1]));const mi=MONTHS.findIndex(x=>l.includes(x)),dm=l.match(/\b(\d{1,2})\b/);if(mi>=0&&dm)return new Date(state.year,mi,Number(dm[1]));return null}
function norm(y){return y<100?2000+y:y}
function parseTime(txt){const m=txt.match(/(\d{1,2})(?:h|:)(\d{0,2})?\s*(?:à|a|-|jusqu(?:’|')?à)\s*(\d{1,2})(?:h|:)(\d{0,2})?/i);if(!m)return{start:state.settings.defaultStart,end:state.settings.defaultEnd};return{start:`${String(m[1]).padStart(2,"0")}:${String(m[2]||"00").padStart(2,"0")}`,end:`${String(m[3]).padStart(2,"0")}:${String(m[4]||"00").padStart(2,"0")}`}}
function monthIn(t){return MONTHS.findIndex(m=>t.toLowerCase().includes(m))}
function localAI(txt){const l=txt.toLowerCase();if(l.includes("combien")||l.includes("payer")||l.includes("récap")||l.includes("recap")){const old=state.month,m=monthIn(l);if(m>=0)state.month=m;const s=sum();const r=`Pour ${MONTHS[state.month]} ${state.year} :\n- ${htxt(s.h)} de garde\n- ${s.days} jour(s) gardé(s)\n- ${s.meals} repas\n- ${s.care} indemnité(s) d’entretien\n- Total estimé : ${euro(s.total)}`;state.month=old;return r}const d=parseDate(l);if(!d)return "Je n’ai pas compris la date. Exemple : Ajoute le 12/06 de 8h à 17h30.";const k=key(d);state.year=d.getFullYear();state.month=d.getMonth();if(l.includes("absent")||l.includes("absence")){const nounou=l.includes("nounou")||l.includes("assistante");state.days[k]={status:nounou?"absence_nounou":"absence_enfant",start:"",end:"",pause:0,meal:false,care:false,note:nounou?"Absence assistante maternelle":"Absence enfant"};return `${human(k)} marqué en ${nounou?"absence nounou":"absence enfant"}.`}if(l.includes("congé")||l.includes("conge")){state.days[k]={status:"conge",start:"",end:"",pause:0,meal:false,care:false,note:"Congé ajouté par l’assistant"};return `${human(k)} marqué en congé.`}const tr=parseTime(txt);state.days[k]={status:l.includes("exception")?"exceptionnel":"garde",start:tr.start,end:tr.end,pause:0,meal:!l.includes("sans repas"),care:!l.includes("sans entretien"),note:"Ajouté par l’assistant"};return `${human(k)} ajouté de ${tr.start} à ${tr.end}. Montant estimé : ${euro(cost(state.days[k]))}.`}
async function ask(e){e.preventDefault();const txt=$("#ask").value.trim();if(!txt)return;state.chat.push({role:"user",text:txt});$("#ask").value="";save();renderChat();let reply="";if(state.settings.aiEndpoint){try{const r=await fetch(state.settings.aiEndpoint,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({message:txt,state})});if(r.ok){const data=await r.json();if(data.state)state=data.state;reply=data.reply||"Action traitée par le serveur IA."}}catch(e){reply=""}}if(!reply)reply=localAI(txt);state.chat.push({role:"bot",text:reply});save();render()}
function bind(){$$('nav button').forEach(b=>b.onclick=()=>show(b.dataset.v));$("#prev").onclick=()=>{const d=new Date(state.year,state.month-1,1);state.year=d.getFullYear();state.month=d.getMonth();save();render()};$("#next").onclick=()=>{const d=new Date(state.year,state.month+1,1);state.year=d.getFullYear();state.month=d.getMonth();save();render()};$("#yearSelect").onchange=e=>{state.year=Number(e.target.value);save();render()};$("#fillMonth").onclick=fillMonth;$("#csv").onclick=exportCsv;$("#print").onclick=printMonth;$("#dayForm").onsubmit=saveDay;$("#deleteDay").onclick=delDay;$("#settingsForm").onsubmit=saveSettings;$("#backup").onclick=backup;$("#import").onchange=e=>importBackup(e.target.files[0]);$("#assistantForm").onsubmit=ask;$$('.examples button').forEach(b=>b.onclick=()=>{$("#ask").value=b.textContent;$("#ask").focus()});$("#dayDate").value=key(new Date())}
window.addEventListener("beforeinstallprompt",e=>{e.preventDefault();installPrompt=e;$("#installBtn").hidden=false;$("#installBtn").onclick=async()=>{installPrompt.prompt();$("#installBtn").hidden=true}});
if("serviceWorker" in navigator)window.addEventListener("load",()=>navigator.serviceWorker.register("sw.js").catch(console.warn));
bind();render();
